"""Byte-identity goldens for the CC/Codex install artifacts (issue #191, AC1).

The heart of the #191 refactor guarantee: however the profile schema grows,
the artifacts the profile-driven writers produce for the two *shipped*
harnesses stay byte-for-byte what they were before the schema landed. The
golden files under ``tests/fixtures/harness_goldens/`` were captured from the
pre-#191 code and are the independent truth source — they are never
regenerated by the suite. A legitimate, intended artifact change edits the
golden in the same commit that changes the writer, and says why.

Machine-dependent inputs are pinned (uv path, project root, vault root) or
normalised out (the repo root inside hook commands becomes ``«REPO»``, via the
format's own string-escaping so the substitution also holds on Windows).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from thinkweave.core import harness, mcp_config

GOLDENS = Path(__file__).parent / "fixtures" / "harness_goldens"

#: Pinned machine-dependent inputs — chosen values are arbitrary but frozen.
UV_PATH = "/pinned/bin/uv"
PROJECT_ROOT = "/pinned/thinkweave"
VAULT_ROOT = "/pinned/vault"


def _escaped(text: str, raw: str) -> str:
    """Replace ``raw`` in ``text`` in its JSON/TOML string-escaped spelling —
    on POSIX that is the identity, on Windows it carries doubled backslashes."""
    return text.replace(json.dumps(raw)[1:-1], "«REPO»")


@pytest.fixture(params=["claude-code", "codex"])
def shipped_profile(
    request, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> harness.HarnessProfile:
    """Each shipped harness's profile, derived from a sandboxed home."""
    if request.param == "codex":
        monkeypatch.setenv("CODEX_HOME", str(tmp_path / ".codex"))
        profile = harness.codex()
    else:
        profile = harness.claude_code(home=tmp_path)
    monkeypatch.setattr(harness, "_OVERRIDE", profile)
    return profile


def _golden(profile_id: str, name: str) -> str:
    path = GOLDENS / profile_id / name
    assert path.exists(), (
        f"golden {path} is missing — it must be captured from the known-good "
        "writer output and committed, never generated on the fly"
    )
    return path.read_text(encoding="utf-8")


class TestHookSettingsBytes:
    def test_installed_settings_reproduce_the_golden(
        self, shipped_profile: harness.HarnessProfile
    ):
        from thinkweave.surfaces.hooks import install as hooks_install

        built = hooks_install._build_installed_settings({})
        text = json.dumps(built, indent=2) + "\n"
        text = _escaped(text, str(hooks_install._repo_root()))
        assert text == _golden(shipped_profile.id, "hooks-settings.json")


class TestMcpConfigBytes:
    def test_written_config_reproduces_the_golden(
        self,
        shipped_profile: harness.HarnessProfile,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ):
        from thinkweave.surfaces.cli import install as inst

        monkeypatch.setattr(inst, "_detect_uv_path", lambda: UV_PATH)
        entry = inst._build_server_entry(Path(PROJECT_ROOT), VAULT_ROOT)
        target = tmp_path / ("out" + shipped_profile.mcp_config.suffix)
        mcp_config.write_entry(target, inst.SERVER_NAME, entry)
        name = "mcp-config" + shipped_profile.mcp_config.suffix
        assert target.read_text(encoding="utf-8") == _golden(
            shipped_profile.id, name
        )


class TestInstructionsBlockBytes:
    def test_rendered_block_reproduces_the_golden(
        self, shipped_profile: harness.HarnessProfile
    ):
        from thinkweave.surfaces.cli import install as inst

        block = inst._render_claude_md_block() + "\n"
        assert block == _golden(shipped_profile.id, "instructions-block.md")
